// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWDq1l6-9X8XZhv6p6_LEEgDzZLEiHnw',
    appId: '1:1007621341675:web:3ece3cb4e25787f8f859ae',
    messagingSenderId: '1007621341675',
    projectId: 'test-f3e47',
    authDomain: 'test-f3e47.firebaseapp.com',
    storageBucket: 'test-f3e47.appspot.com',
    measurementId: 'G-JJLFB4X69N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtpvD84MMwANHPrWbR6A7b8k8QorGO05s',
    appId: '1:1007621341675:android:c111d37e0e132c27f859ae',
    messagingSenderId: '1007621341675',
    projectId: 'test-f3e47',
    storageBucket: 'test-f3e47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiVMdKlC0YVgJZ4H3O5rqF30R97_P-Og',
    appId: '1:1007621341675:ios:a2a6ad07b3ee2393f859ae',
    messagingSenderId: '1007621341675',
    projectId: 'test-f3e47',
    storageBucket: 'test-f3e47.appspot.com',
    iosClientId: '1007621341675-j8nukmk3o9a3af4p0aj8f06vfn8r4h0s.apps.googleusercontent.com',
    iosBundleId: 'com.desolate.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiVMdKlC0YVgJZ4H3O5rqF30R97_P-Og',
    appId: '1:1007621341675:ios:165c59b473947ee9f859ae',
    messagingSenderId: '1007621341675',
    projectId: 'test-f3e47',
    storageBucket: 'test-f3e47.appspot.com',
    iosClientId: '1007621341675-69pqhlj92c08l4d33m1g922nobmk38ur.apps.googleusercontent.com',
    iosBundleId: 'com.desolate.mynotes.RunnerTests',
  );
}
